# SPDX-License-Identifier: Apache-2.0
---

- name: Stop and disable service firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld' in ansible_facts.packages"
