# SPDX-License-Identifier: Apache-2.0
---
# Variables specific on MS Azure platform, Virtual Machines
#
# TODO: make sure to first respect 'ha_cluster' native variables

# The packages of the following lists will be installed by the 'ha_cluster' Linux System Role.
# Any packages that are pre-requisites for variable construction must be installed before, e.g.
# in the preconfigure-* tasks.
__sap_ha_pacemaker_cluster_fence_agent_packages_platform:
  "{{ __sap_ha_pacemaker_cluster_fence_agent_packages_dict.cloud_msazure_vm | default([]) }}"

__sap_ha_pacemaker_cluster_platform_extra_packages:
  "{{ __sap_ha_pacemaker_cluster_platform_extra_packages_dict.cloud_msazure_vm | default([]) }}"

__sap_ha_pacemaker_cluster_repos:
  "{{ __sap_ha_pacemaker_cluster_repos_dict.cloud_msazure_vm | default([]) }}"


# Stonith dictionary for default stonith agents.
# Custom stonith resource can be defined using sap_ha_pacemaker_cluster_stonith_custom
__sap_ha_pacemaker_cluster_stonith_default_dict:
  fence_azure_arm:
    id: "rsc_fence_azure_arm"
    agent: "stonith:fence_azure_arm"
    options:
      msi: true
      subscriptionId: "{{ sap_ha_pacemaker_cluster_msazure_subscription_id }}"
      resourceGroup: "{{ sap_ha_pacemaker_cluster_msazure_resource_group }}"

# Select __sap_ha_pacemaker_cluster_stonith_default
__sap_ha_pacemaker_cluster_stonith_default:
  "{{ __sap_ha_pacemaker_cluster_stonith_default_dict.fence_azure_arm }}"


# Default corosync options - Platform specific
__sap_ha_pacemaker_cluster_corosync_totem_platform:
  options:
    token: 30000

# Platform specific VIP handling
sap_ha_pacemaker_cluster_vip_method: azure_lb

# The VIP layer consists of 2 components - the VIP and the health check resource
sap_ha_pacemaker_cluster_vip_group_prefix: group_

sap_ha_pacemaker_cluster_healthcheck_hana_primary_port: "620{{ sap_ha_pacemaker_cluster_hana_instance_nr }}"
sap_ha_pacemaker_cluster_healthcheck_hana_secondary_port: >-
  {% if sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address | length > 0 -%}
    620{{ sap_ha_pacemaker_cluster_hana_instance_nr | int + 1 }}
  {%- else %}{% endif %}
sap_ha_pacemaker_cluster_healthcheck_nwas_abap_ascs_port: "620{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_instance_nr }}"
sap_ha_pacemaker_cluster_healthcheck_nwas_abap_ers_port: "620{{ sap_ha_pacemaker_cluster_nwas_abap_ers_instance_nr }}"
sap_ha_pacemaker_cluster_healthcheck_nwas_abap_pas_port: "620{{ sap_ha_pacemaker_cluster_nwas_abap_pas_instance_nr }}"
sap_ha_pacemaker_cluster_healthcheck_nwas_abap_aas_port: "620{{ sap_ha_pacemaker_cluster_nwas_abap_aas_instance_nr }}"

__sap_ha_pacemaker_cluster_available_vip_agents:

  # IPaddr2 requires a Virtual IP within a common Network (i.e. 1 VLAN / 1 VPC / 1 VNet),
  # one or more Subnets may be used.
  # With this design restriction, IPaddr2 is only to be used for High Availability within
  # a single location (i.e. 1 Availability Zone / Datacenter / Location within 1 Region)
  ipaddr:
    agent: "ocf:heartbeat:IPaddr2"

  # Use nc/socat to listen for and respond to health check probe monitoring requests from
  # Azure Load Balancer, if failure to respond then the Load Balancer will perform failover activities
  azure_lb:
    agent: "ocf:heartbeat:azure-lb"
    with: ipaddr
