# SPDX-License-Identifier: Apache-2.0
---
# Variables specific on AWS platform, EC2 Virtual Servers
#
# TODO: make sure to first respect 'ha_cluster' native variables

# Package definition
__sap_ha_pacemaker_cluster_fence_agent_packages_platform:
  "{{ __sap_ha_pacemaker_cluster_fence_agent_packages_dict.cloud_aws_ec2_vs | default([]) }}"

__sap_ha_pacemaker_cluster_platform_extra_packages:
  "{{ __sap_ha_pacemaker_cluster_platform_extra_packages_dict.cloud_aws_ec2_vs | default([]) }}"

__sap_ha_pacemaker_cluster_repos:
  "{{ __sap_ha_pacemaker_cluster_repos_dict.cloud_aws_ec2_vs | default([]) }}"


# Stonith dictionary for default stonith agents.
# Custom stonith resource can be defined using sap_ha_pacemaker_cluster_stonith_custom
__sap_ha_pacemaker_cluster_stonith_default_dict:
  fence_aws:
    id: "rsc_fence_aws"
    # AWS Fence agent is not recommended.
    agent: "stonith:fence_aws"
    options:
      # Fencing action delay is recommended. Default: 0
      # Production pcmk_delay_max is recommended 30-60
      pcmk_delay_max: 15
      # AWS Credentials are not defined here, because they override attached
      # IAM Role or IAM Instance Profile
      # access_key: "{{ sap_ha_pacemaker_cluster_aws_access_key_id }}"
      # secret_key: "{{ sap_ha_pacemaker_cluster_aws_secret_access_key }}"
      # region: "{{ sap_ha_pacemaker_cluster_aws_region }}"

  external_ec2:
    id: "rsc_fence_aws"
    # SUSE Recommends stonith:external/ec2 instead of fence_aws
    agent: "stonith:external/ec2"
    options:
      # Fencing action delay is recommended. Default: 0
      # Production pcmk_delay_max is recommended 30-60
      pcmk_delay_max: 15
      tag: pacemaker  # tag instance with pacemaker: {{ ansible_hostname }}
      # profile: default  # Additional tag to use awscli config

# Select __sap_ha_pacemaker_cluster_stonith_default
# SUSE does not support stonith:fence_aws
__sap_ha_pacemaker_cluster_stonith_default:
  "{{ __sap_ha_pacemaker_cluster_stonith_default_dict.external_ec2 if ansible_os_family == 'Suse'
   else __sap_ha_pacemaker_cluster_stonith_default_dict.fence_aws }}"


# Default corosync options - Platform specific
__sap_ha_pacemaker_cluster_corosync_totem_platform:
  options:
    token: 30000


# Platform specific VIP handling
sap_ha_pacemaker_cluster_vip_method: aws_vpc_move_ip
sap_ha_pacemaker_cluster_vip_group_prefix: ''  # the default supported VIP agent is a single resource only

__sap_ha_pacemaker_cluster_available_vip_agents:
  # Testing only! Not officially supported for SAP on AWS.
  ipaddr:
    agent: "ocf:heartbeat:IPaddr2"

  # Testing only! Not officially supported for SAP on AWS. Updates VM Instance network interface (ENI) with Secondary Private IP.
  awsvip:
    agent: "ocf:heartbeat:awsvip"
    with: ipaddr

  # Supported agent to manage Virtual/Overlay IPs for SAP on AWS by updating VPC Routing Table.
  aws_vpc_move_ip:
    agent: "ocf:heartbeat:aws-vpc-move-ip"

# RHEL 8.6 and later:
# Services that must be disabled and stopped for the VIP to work
# otherwise AWS cloud-init keeps deleting the IP
sap_ha_pacemaker_cluster_disable_services:
  - nm-cloud-setup.timer
  - nm-cloud-setup
