# SPDX-License-Identifier: Apache-2.0
---
# Variables specific on IBM PowerVM hypervisor, Virtual Machines (LPAR)
# TODO: rename this file to match the actual "chassis_asset_tag" output
# TODO: make sure to first respect 'ha_cluster' native variables

__sap_ha_pacemaker_cluster_fence_agent_packages_platform:
  "{{ __sap_ha_pacemaker_cluster_fence_agent_packages_dict.hyp_ibmpower_vm | default([]) }}"

__sap_ha_pacemaker_cluster_platform_extra_packages:
  "{{ __sap_ha_pacemaker_cluster_platform_extra_packages_dict.hyp_ibmpower_vm | default([]) }}"

__sap_ha_pacemaker_cluster_repos:
  "{{ __sap_ha_pacemaker_cluster_repos_dict.hyp_ibmpower_vm | default([]) }}"


# Stonith dictionary for default stonith agents.
# Custom stonith resource can be defined using sap_ha_pacemaker_cluster_stonith_custom
__sap_ha_pacemaker_cluster_stonith_default_dict:
  fence_lpar:
    id: "rsc_fence_lpar"
    agent: "stonith:fence_lpar"
    options:
      ip: "{{ sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host }}"
      ipport: "{{ sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_port }}"
      username: "{{ sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_login }}"
      password: "{{ sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_login_password }}"
      hmc_version: "{{ sap_ha_pacemaker_cluster_ibmpower_vm_hmc_host_version | default('4') }}"
      managed: "{{ sap_ha_pacemaker_cluster_ibmpower_vm_hmc_system_host_mtms }}"
      # Identified during execution initial tasks, populated when variables are imported

      # plug: "{{ sap_ha_pacemaker_cluster_ibmpower_vm_hmc_system_partition_name }}"
      # Unnecessary when using pcmk_host_map. Identified during execution initial tasks, populated when variables are imported

      pcmk_reboot_retries: 4
      pcmk_reboot_timeout: 600
      pcmk_monitor_timeout: 600
      pcmk_status_timeout: 60
      power_timeout: 240

# Select __sap_ha_pacemaker_cluster_stonith_default
__sap_ha_pacemaker_cluster_stonith_default:
  "{{ __sap_ha_pacemaker_cluster_stonith_default_dict.fence_lpar }}"


# Platform specific VIP handling
sap_ha_pacemaker_cluster_vip_method: ipaddr

__sap_ha_pacemaker_cluster_available_vip_agents:

  # IPaddr2 requires a Virtual IP within a common Network (i.e. 1 VLAN / 1 VPC / 1 VNet),
  # one or more Subnets may be used
  # With this design restriction, IPaddr2 is only to be used for High Availability within
  # a single location (i.e. 1 Availability Zone / Datacenter / Location within 1 Region)
  ipaddr:
    agent: "ocf:heartbeat:IPaddr2"
