---
##
# Call this playbook interactively with
#  ansible-playbook community.sap_install.sap_hana_preconfigure
#
# or alternatively unattended with
#  ansible-playbook community.sap_install.sap_hana_preconfigure -e @myvars.yml
#
# The file myvars. yaml needs to contain the following variables
#
- name: Playbook Usage
  hosts: localhost
  tasks:
    - name: Playbook Usage
      ansible.builtin.debug:
        msg: |-
          *****************************************************************************
          * sap_hana_preconfigure                                                     *
          *                                                                           *
          * This playbook is used to prepare an SAP HANA system.                      *
          * The minimum viable parameters to succussfully prepare your system for an  *
          * SAP HANA installation will be asked.                                      *
          * Useful defaults will be set, so that it is save to just press enter       *
          *****************************************************************************

- name: Collecting Variables
  hosts: localhost

  vars_prompt:
    - name: "sap_systems"
      prompt: "Enter comma separated list of systems, you want to prepare for SAP HANA"
      private: false
      default: "localhost"

    - name: "sap_domain"
      prompt: "Enter DNS Domainname of your SAP systems (leave empty for using system default: "
      private: false
      default: "{{ sap_domain | d('') }}"

    - name: "sap_update_hosts"
      prompt: "Do you want the system to update /etc/hosts for SAP (y/n)"
      private: false
      default: "y"

    - name: "sap_update"
      prompt: "Do you want to update the system? (y/n)"
      private: false
      default: "n"

    - name: "sap_fail_if_reboot_required"
      prompt: "Do you want to stop with an error if the system needs a reboot? (y/n)"
      private: false
      default: "n"

    - name: "sap_reboot"
      prompt: "Do you want to reboot the system if required? (y/n)"
      private: false
      default: "n"

  tasks:
    - name: Prepare inventory
      when: sap_systems != 'localhost'
      ansible.builtin.add_host:
        groups: sap_hana_prepare_hosts
        name: '{{ item }}'
      loop: '{{ sap_systems | split(",") | list }}'

    - name: Configure Role Variables
      ansible.builtin.set_fact:
        sap_domain: '{{ sap_domain }}'
        ### redhat.sap_install.sap_general_preconfigure
        sap_general_preconfigure_modify_etc_hosts: '{{ (sap_update_hosts == "y") | ternary(true, false) }}'
        sap_general_preconfigure_update: '{{ (sap_update == "y") | ternary(true, false) }}'
        sap_general_preconfigure_fail_if_reboot_required: '{{ (sap_fail_if_reboot_required == "n") | ternary(false, true) }}'
        # sap_general_preconfigure_system_roles_collection: 'redhat.rhel_system_roles'
        ### redhat.sap_install.sap_hana_preconfigure
        sap_hana_preconfigure_update: '{{ (sap_update == "y") | ternary(true, false) }}'
        sap_hana_preconfigure_fail_if_reboot_required: '{{ (sap_fail_if_reboot_required == "n") | ternary(false, true) }}'
        sap_hana_preconfigure_reboot_ok: '{{ (sap_reboot == "n") | ternary(false, true) }}'
        # sap_hana_preconfigure_system_roles_collection: 'redhat.rhel_system_roles'

- name: Run sap_hana_prepare_exec playbook
  ansible.builtin.import_playbook: sap_hana_preconfigure_exec.yml
  vars:
    sap_playbook_parameter_confirm: true
    sap_hana_group: "{{ ( groups['sap_hana_prepare_hosts'] is defined) | ternary ('sap_hana_prepare_hosts','localhost') }}"
    sap_domain: "{{ hostvars['localhost']['sap_domain'] }}"
    sap_general_preconfigure_modify_etc_hosts: "{{ hostvars['localhost']['sap_general_preconfigure_modify_etc_hosts'] }}"
    sap_general_preconfigure_update: "{{ hostvars['localhost']['sap_general_preconfigure_update'] }}"
    sap_general_preconfigure_fail_if_reboot_required: "{{ hostvars['localhost']['sap_general_preconfigure_fail_if_reboot_required'] }}"
    sap_hana_preconfigure_update: "{{ hostvars['localhost']['sap_hana_preconfigure_update'] }}"
    sap_hana_preconfigure_fail_if_reboot_required: "{{ hostvars['localhost']['sap_hana_preconfigure_fail_if_reboot_required'] }}"
    sap_hana_preconfigure_reboot_ok: "{{ hostvars['localhost']['sap_hana_preconfigure_reboot_ok'] }}"
