# SPDX-License-Identifier: Apache-2.0
---
# Detect presence of SAPHanaSR-angi package before loading HANA variables
# Detection of package availability was chosen instead of OS version check.
# SAPHanaSR-angi will be retrofitted to older SP repositories in future.
- name: "SAP HA Prepare Pacemaker - Detect SAPHanaSR-angi availability"
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}/pre_steps_hana.yml"
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0


- name: "SAP HA Prepare Pacemaker - Include HANA landscape specific variables"
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ include_item }}.yml"
  loop: "{{ __host_type_list | flatten }}"
  loop_control:
    loop_var: include_item
    label: "{{ include_item }}.yml"
  vars:
    __host_type_list:
      - "{{ sap_ha_pacemaker_cluster_host_type | d('hana_scaleup_perf') }}"
  when:
    - "(role_path + '/vars/' + include_item + '.yml') is file"


# Disable concurrent-fencing for Scale-up scenario.
# This assignment cannot be in scaleup var file, because it results in nested error.
- name: "SAP HA Prepare Pacemaker - Disable concurrent-fencing in properties"
  ansible.builtin.set_fact:
    sap_ha_pacemaker_cluster_cluster_properties:
      "{{ sap_ha_pacemaker_cluster_cluster_properties | combine({'concurrent-fencing': false})
      if sap_ha_pacemaker_cluster_cluster_properties['concurrent-fencing'] is defined
      else sap_ha_pacemaker_cluster_cluster_properties }}"
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana_scaleup') | length > 0


# Calculate private variables
- name: "SAP HA Prepare Pacemaker - Set primary variables (HANA)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_hana_sid:
      "{{ sap_ha_pacemaker_cluster_hana_sid | d(sap_hana_sid) | d('') | upper }}"

    # TODO: Remove backwards compatibility sap_ha_pacemaker_cluster_hana_instance_number
    __sap_ha_pacemaker_cluster_hana_instance_nr:
      "{{ sap_ha_pacemaker_cluster_hana_instance_nr | d(sap_ha_pacemaker_cluster_hana_instance_number)
      | d(sap_hana_instance_number) | d('') }}"


- name: "SAP HA Prepare Pacemaker - Set cluster resource variables: Primitives (HANA)"
  ansible.builtin.set_fact:
    # SAP Hana
    __sap_ha_pacemaker_cluster_hana_resource_name:
      "{{ sap_ha_pacemaker_cluster_hana_resource_name
      | d('rsc_SAPHana_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    __sap_ha_pacemaker_cluster_hana_resource_clone_name:
      "{{ sap_ha_pacemaker_cluster_hana_resource_clone_name
      | d('cln_SAPHana_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    __sap_ha_pacemaker_cluster_hana_resource_clone_msl_name:
      "{{ sap_ha_pacemaker_cluster_hana_resource_clone_msl_name
      | d('msl_SAPHana_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    # SAP Hana Controller
    __sap_ha_pacemaker_cluster_hanacontroller_resource_name:
      "{{ sap_ha_pacemaker_cluster_hanacontroller_resource_name
      | d('rsc_SAPHanaCon_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    __sap_ha_pacemaker_cluster_hanacontroller_resource_clone_name:
      "{{ sap_ha_pacemaker_cluster_hanacontroller_resource_clone_name
      | d('mst_SAPHanaCon_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    # SAP Hana Topology
    __sap_ha_pacemaker_cluster_hana_topology_resource_name:
      "{{ sap_ha_pacemaker_cluster_hana_topology_resource_name
      | d('rsc_SAPHanaTop_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    __sap_ha_pacemaker_cluster_hana_topology_resource_clone_name:
      "{{ sap_ha_pacemaker_cluster_hana_topology_resource_clone_name
      | d('cln_SAPHanaTop_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    # SAP Hana Filesystem
    __sap_ha_pacemaker_cluster_hana_filesystem_resource_name:
      "{{ sap_ha_pacemaker_cluster_hana_filesystem_resource_name
      | d('rsc_SAPHanaFil_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    __sap_ha_pacemaker_cluster_hana_filesystem_resource_clone_name:
      "{{ sap_ha_pacemaker_cluster_hana_filesystem_resource_clone_name
      | d('cln_SAPHanaFil_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"


- name: "SAP HA Prepare Pacemaker - Set cluster resource variables: Constraints (HANA)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_hana_order_topology_hana_name:
      "{{ sap_ha_pacemaker_cluster_hana_order_topology_hana_name
      | d('ord_saphana_saphanatop_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) }}"

    __sap_ha_pacemaker_cluster_hana_colocation_hana_vip_primary_name:
      "{{ sap_ha_pacemaker_cluster_hana_colocation_hana_vip_primary_name
      | d('col_saphana_vip_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_primary' }}"

    __sap_ha_pacemaker_cluster_hana_colocation_hana_vip_secondary_name:
      "{{ sap_ha_pacemaker_cluster_hana_colocation_hana_vip_secondary_name
      | d('col_saphana_vip_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_readonly' }}"

    __sap_ha_pacemaker_cluster_hana_order_hana_vip_primary_name:
      "{{ sap_ha_pacemaker_cluster_hana_order_hana_vip_primary_name
      | d('ord_saphana_vip_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_primary' }}"

    __sap_ha_pacemaker_cluster_hana_order_hana_vip_secondary_name:
      "{{ sap_ha_pacemaker_cluster_hana_order_hana_vip_secondary_name
      | d('ord_saphana_vip_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_readonly' }}"


- name: "SAP HA Prepare Pacemaker - Set cluster resource variables: VIP (HANA)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_vip_hana_primary_ip_address:
      "{{ sap_ha_pacemaker_cluster_vip_hana_primary_ip_address | d('') }}"

    __sap_ha_pacemaker_cluster_vip_hana_primary_resource_name:
      "{{ sap_ha_pacemaker_cluster_vip_hana_primary_resource_name
      | d('rsc_vip_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_primary' }}"

    __sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name:
      "{{ sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name
      | d('rsc_vip_health_check_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_primary' }}"

    __sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address:
      "{{ sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address | d('') }}"

    __sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name:
      "{{ sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name
      | d('rsc_vip_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_readonly' }}"

    __sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name:
      "{{ sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name
      | d('rsc_vip_health_check_' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '_HDB' ~ __sap_ha_pacemaker_cluster_hana_instance_nr) ~ '_readonly' }}"

    __sap_ha_pacemaker_cluster_healthcheck_hana_primary_id:
      "{{ sap_ha_pacemaker_cluster_healthcheck_hana_primary_id | d(__sap_ha_pacemaker_cluster_hana_sid ~ 'prim') }}"

    __sap_ha_pacemaker_cluster_healthcheck_hana_secondary_id:
      "{{ sap_ha_pacemaker_cluster_healthcheck_hana_secondary_id | d(__sap_ha_pacemaker_cluster_hana_sid ~ 'ro') }}"


- name: "SAP HA Prepare Pacemaker - Set variables: Other (HANA)"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_hana_global_ini_path:
      "{{ sap_ha_pacemaker_cluster_hana_global_ini_path
      | d('/usr/sap/' ~ __sap_ha_pacemaker_cluster_hana_sid ~ '/SYS/global/hdb/custom/config/global.ini') }}"
